------------------------------------
-- Table creation for Videos.eomodeld
------------------------------------

CREATE TABLE MUSIC_VIDEO (ARTIST_ID NUMBER(9) NOT NULL, GENRE_ID NUMBER(9) NOT NULL, LABEL_ID NUMBER(9) NOT NULL, LANGUAGE_ID NUMBER(9) , TITLE VARCHAR2(255) NOT NULL, VIDEO_ID NUMBER(9) NOT NULL);
CREATE TABLE SEASON (DETAIL VARCHAR2(2095) NOT NULL, NO NUMBER(9) NOT NULL, SEASON_ID NUMBER(9) NOT NULL, SHOW_ID NUMBER(9) NOT NULL, TITLE VARCHAR2(255) NOT NULL);
CREATE TABLE SHORT_FILM (STUDIO_ID NUMBER(9) NOT NULL, TITLE VARCHAR2(255) NOT NULL, VIDEO_ID NUMBER(9) NOT NULL);
CREATE TABLE TV_SHOW (TITLE VARCHAR2(2095) NOT NULL, SHOW_ID NUMBER(9) NOT NULL, STUDIO_ID NUMBER(9) NOT NULL);

-- Primary key constraintS
ALTER TABLE MUSIC_VIDEO ADD PRIMARY KEY (VIDEO_ID);
ALTER TABLE SEASON ADD PRIMARY KEY (SEASON_ID);
ALTER TABLE SHORT_FILM ADD PRIMARY KEY (VIDEO_ID);
ALTER TABLE TV_SHOW ADD PRIMARY KEY (SHOW_ID);
ALTER TABLE SEASON ADD CONSTRAINT SEASON_show_FK FOREIGN KEY (SHOW_ID) REFERENCES TV_SHOW (SHOW_ID) DEFERRABLE INITIALLY DEFERRED;

-- Primary key support
create sequence MUSIC_VIDEO_SEQ;

-- Synonyms
create public synonym MUSIC_VIDEO for MUSIC_VIDEO;
create public synonym SEASON for SEASON;
create public synonym SHORT_FILM for SHORT_FILM;
create public synonym TV_SHOW for TV_SHOW;
create public synonym MUSIC_VIDEO_SEQ for MUSIC_VIDEO_SEQ;

------------------------------------
-- Table creation for Assets.eomodeld
------------------------------------

CREATE TABLE ASSET (ASSET_ID NUMBER NOT NULL, ENTITY_NAME VARCHAR2(50) NOT NULL, TOKEN VARCHAR2(255) NOT NULL);

-- Primary key constraints
ALTER TABLE ASSET ADD PRIMARY KEY (ASSET_ID);

-- Primary key support
create sequence ASSET_SEQ;

-- Synonyms
create public synonym ASSET for ASSET;

------------------------------------
-- Table creation for Studios.eomodeld
------------------------------------

CREATE TABLE STUDIO (ENTITY_NAME VARCHAR2(50) NOT NULL, NAME VARCHAR2(255) NOT NULL, PARENT_STUDIO_ID NUMBER(9) , STUDIO_ID NUMBER(9) NOT NULL);

-- Primary key constraints
ALTER TABLE STUDIO ADD PRIMARY KEY (STUDIO_ID);
ALTER TABLE STUDIO ADD CONSTRAINT STUDIO_parent_FK FOREIGN KEY (PARENT_STUDIO_ID) REFERENCES STUDIO (STUDIO_ID) DEFERRABLE INITIALLY DEFERRED;

-- Primary key support
create sequence STUDIO_SEQ;

-- Synonyms
create public synonym STUDIO for STUDIO;

------------------------------------
-- Table creation for Products.eomodeld
------------------------------------

CREATE TABLE PRODUCT (CONTENT_ID NUMBER(9) NOT NULL, ENTITY_NAME VARCHAR2(50) NOT NULL, PRICE NUMBER(10,2) NOT NULL, PRODUCT_ID NUMBER(9) NOT NULL, STORE_ID NUMBER(9) NOT NULL);

-- Primary key constraints
ALTER TABLE PRODUCT ADD PRIMARY KEY (PRODUCT_ID);

-- Primary key support
create sequence PRODUCT_SEQ;

-- Synonyms
create public synonym PRODUCT for PRODUCT;

------------------------------------
-- Table creation for Podcasts.eomodeld
------------------------------------

CREATE TABLE PODCAST (DETAIL VARCHAR2(2095) , PODCAST_ID NUMBER(9) NOT NULL, TITLE VARCHAR2(255) NOT NULL);

-- Primary key constraints
ALTER TABLE PODCAST ADD PRIMARY KEY (PODCAST_ID);

-- Primary key support
create sequence PODCAST_SEQ;

-- Synonyms
create public synonym PODCAST for PODCAST;

------------------------------------
-- Table creation for Playlists.eomodeld
------------------------------------

CREATE TABLE PLAYLIST (ARTIST_ID NUMBER(9) , COVER_ART_ID NUMBER , ENTITY_NAME VARCHAR2(50) NOT NULL, GENRE_ID NUMBER(9) NOT NULL, LABEL_ID NUMBER(9) NOT NULL, LANGUAGE_ID NUMBER(9) , PARENTAL_ADVISORY_ID NUMBER(9) , PLAYLIST_ID NUMBER(9) NOT NULL, THUMBNAIL_ID NUMBER , TITLE VARCHAR2(255) NOT NULL);

-- Primary key constraints
ALTER TABLE PLAYLIST ADD PRIMARY KEY (PLAYLIST_ID);

-- Primary key support
create sequence PLAYLIST_SEQ;

-- Synonyms
create public synonym PLAYLIST for PLAYLIST;

------------------------------------
-- Table creation for Music.eomodeld
------------------------------------

CREATE TABLE ARTIST_COLLABORATION (ARTIST_ID NUMBER NOT NULL, COLLABORATION_ID NUMBER NOT NULL);
CREATE TABLE ARTIST_GROUP (ARTIST_ID NUMBER NOT NULL, GROUP_ID NUMBER NOT NULL);
CREATE TABLE BOX_SET (ARTIST_ID NUMBER(9) NOT NULL, BOX_SET_ID NUMBER(9) NOT NULL, GENRE_ID NUMBER(9) NOT NULL, LABEL_ID NUMBER(9) NOT NULL, TITLE VARCHAR2(255) NOT NULL);
CREATE TABLE BOX_SET_PLAYLIST (PLAYLIST_ID NUMBER(9) NOT NULL, BOX_SET_ID NUMBER(9) NOT NULL);
CREATE TABLE COMPOSER (COMPOSER_ID NUMBER NOT NULL, NAME VARCHAR2(255) NOT NULL);
CREATE TABLE GENRE (GENRE_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL, PARENT_GENRE_ID NUMBER(9) );
CREATE TABLE PARENTAL_ADVISORY (PARENTAL_ADVISORY_ID NUMBER(9) NOT NULL, TYPE VARCHAR2(50) NOT NULL);
CREATE TABLE SONG (ARTIST_ID NUMBER(9) NOT NULL, NO NUMBER(9) NOT NULL, PLAYLIST_ID NUMBER(9) NOT NULL, TITLE VARCHAR2(255) NOT NULL, TRACK_ID NUMBER(9) NOT NULL);
CREATE TABLE SONG_COMPOSER (COMPOSER_ID NUMBER NOT NULL, TRACK_ID NUMBER NOT NULL);

-- Primary key constraints
ALTER TABLE ARTIST_COLLABORATION ADD PRIMARY KEY (ARTIST_ID, COLLABORATION_ID);
ALTER TABLE ARTIST_GROUP ADD PRIMARY KEY (GROUP_ID, ARTIST_ID);
ALTER TABLE BOX_SET ADD PRIMARY KEY (BOX_SET_ID);
ALTER TABLE BOX_SET_PLAYLIST ADD PRIMARY KEY (BOX_SET_ID, PLAYLIST_ID);
ALTER TABLE COMPOSER ADD PRIMARY KEY (COMPOSER_ID);
ALTER TABLE GENRE ADD PRIMARY KEY (GENRE_ID);
ALTER TABLE PARENTAL_ADVISORY ADD PRIMARY KEY (PARENTAL_ADVISORY_ID);
ALTER TABLE SONG ADD PRIMARY KEY (TRACK_ID);
ALTER TABLE SONG_COMPOSER ADD PRIMARY KEY (COMPOSER_ID, TRACK_ID);
ALTER TABLE BOX_SET ADD CONSTRAINT BOX_SET_genre_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRE (GENRE_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE BOX_SET_PLAYLIST ADD CONSTRAINT BOX_SET_PLAYLIST_boxSet_FK FOREIGN KEY (BOX_SET_ID) REFERENCES BOX_SET (BOX_SET_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE GENRE ADD CONSTRAINT GENRE_parent_FK FOREIGN KEY (PARENT_GENRE_ID) REFERENCES GENRE (GENRE_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SONG_COMPOSER ADD CONSTRAINT SONG_COMPOSER_song_FK FOREIGN KEY (TRACK_ID) REFERENCES SONG (TRACK_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE SONG_COMPOSER ADD CONSTRAINT SONG_COMPOSER_composer_FK FOREIGN KEY (COMPOSER_ID) REFERENCES COMPOSER (COMPOSER_ID) DEFERRABLE INITIALLY DEFERRED;

-- Primary key support
create sequence ARTIST_COLLABORATION_SEQ;
create sequence ARTIST_GROUP_SEQ;
create sequence BOX_SET_SEQ;
create sequence BOX_SET_PLAYLIST_SEQ;
create sequence COMPOSER_SEQ;
create sequence GENRE_SEQ;
create sequence PARENTAL_ADVISORY_SEQ;
create sequence SONG_SEQ;

-- Synonyms
create public synonym ARTIST_COLLABORATION for ARTIST_COLLABORATION;
create public synonym ARTIST_GROUP for ARTIST_GROUP;
create public synonym BOX_SET for BOX_SET;
create public synonym BOX_SET_PLAYLIST for BOX_SET_PLAYLIST;
create public synonym COMPOSER for COMPOSER;
create public synonym GENRE for GENRE;
create public synonym PARENTAL_ADVISORY for PARENTAL_ADVISORY;
create public synonym SONG for SONG;
create public synonym SONG_COMPOSER for SONG_COMPOSER;

------------------------------------
-- Table creation for Languages.eomodeld
------------------------------------

CREATE TABLE LANGUAGE (ENTITY_NAME VARCHAR2(255) NOT NULL, LANGUAGE_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL);

-- Primary key constraints
ALTER TABLE LANGUAGE ADD PRIMARY KEY (LANGUAGE_ID);

-- Primary key support
create sequence LANGUAGE_SEQ;

-- Synonyms
create public synonym LANGUAGE for LANGUAGE;

------------------------------------
-- Table creation for Labels.eomodeld
------------------------------------

CREATE TABLE LABEL (ENTITY_NAME VARCHAR2(50) NOT NULL, LABEL_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL, PARENT_LABEL_ID NUMBER(9) );

-- Primary key constraints
ALTER TABLE LABEL ADD PRIMARY KEY (LABEL_ID);
ALTER TABLE LABEL ADD CONSTRAINT LABEL_parent_FK FOREIGN KEY (PARENT_LABEL_ID) REFERENCES LABEL (LABEL_ID) DEFERRABLE INITIALLY DEFERRED;

-- Primary key support
create sequence LABEL_SEQ;

-- Synonyms
create public synonym LABEL for LABEL;

------------------------------------
-- Table creation for Episodes.eomodeld
------------------------------------

CREATE TABLE EPISODE (TITLE VARCHAR2(2095) , ENTITY_NAME VARCHAR2(50) NOT NULL, EPISODE_ID NUMBER(9) NOT NULL, RELEASE_DATE DATE NOT NULL, PODCAST_ID NUMBER(9) , SEASON_ID NUMBER(9) );

-- Primary key constraints
ALTER TABLE EPISODE ADD PRIMARY KEY (EPISODE_ID);

-- Primary key support
create sequence EPISODE_SEQ;

-- Synonyms
create public synonym EPISODE for EPISODE;

------------------------------------
-- Table creation for Commerce.eomodeld
------------------------------------

CREATE TABLE COUNTRY (COUNTRY_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL, storeID NUMBER(9) );
CREATE TABLE COUNTRY_LANGUAGE (COUNTRY_ID NUMBER(9) NOT NULL, LANGUAGE_ID NUMBER(9) NOT NULL);
CREATE TABLE CURRENCY (CURRENCY_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL);
CREATE TABLE STORE (CURRENCY_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL, storeID NUMBER(9) NOT NULL);

-- Primary key constraints
ALTER TABLE COUNTRY ADD PRIMARY KEY (COUNTRY_ID);
ALTER TABLE COUNTRY_LANGUAGE ADD PRIMARY KEY (COUNTRY_ID, LANGUAGE_ID);
ALTER TABLE CURRENCY ADD PRIMARY KEY (CURRENCY_ID);
ALTER TABLE STORE ADD PRIMARY KEY (storeID);
ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_store_FK FOREIGN KEY (storeID) REFERENCES STORE (storeID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE COUNTRY_LANGUAGE ADD CONSTRAINT COUNTRY_LANGUAGE_country_FK FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (COUNTRY_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE STORE ADD CONSTRAINT STORE_currency_FK FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (CURRENCY_ID) DEFERRABLE INITIALLY DEFERRED;

-- Primary key support
create sequence COUNTRY_SEQ;
create sequence COUNTRY_LANGUAGE_SEQ;
create sequence CURRENCY_SEQ;
create sequence STORE_SEQ;

-- Synonyms
create public synonym COUNTRY for COUNTRY;
create public synonym COUNTRY_LANGUAGE for COUNTRY_LANGUAGE;
create public synonym CURRENCY for CURRENCY;
create public synonym STORE for STORE;

------------------------------------
-- Table creation for AudioBooks.eomodeld
------------------------------------

CREATE TABLE AUDIO_BOOK (AUDIO_BOOK_ID NUMBER(9) NOT NULL, NARRATOR_ID NUMBER(9) , PROVIDER_ID NUMBER(9) NOT NULL, TITLE VARCHAR2(255) NOT NULL);
CREATE TABLE AUDIO_BOOK_AUTHOR (AUDIO_BOOK_ID NUMBER NOT NULL, AUTHOR_ID NUMBER NOT NULL);
CREATE TABLE AUDIO_BOOK_CATEGORY (AUDIO_BOOK_ID NUMBER(9) NOT NULL, CATEGORY_ID NUMBER(9) NOT NULL);
CREATE TABLE AUTHOR (AUTHOR_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL);
CREATE TABLE CATEGORY (CATEGORY_ID NUMBER(9) NOT NULL, NAME VARCHAR2(255) NOT NULL, PARENT_CATEGORY_ID NUMBER(9) );
CREATE TABLE PROVIDER (NAME VARCHAR2(255) NOT NULL, PROVIDER_ID NUMBER(9) NOT NULL);

-- Primary key constraints
ALTER TABLE AUDIO_BOOK ADD PRIMARY KEY (AUDIO_BOOK_ID);
ALTER TABLE AUDIO_BOOK_AUTHOR ADD PRIMARY KEY (AUDIO_BOOK_ID, AUTHOR_ID);
ALTER TABLE AUDIO_BOOK_CATEGORY ADD PRIMARY KEY (AUDIO_BOOK_ID, CATEGORY_ID);
ALTER TABLE AUTHOR ADD PRIMARY KEY (AUTHOR_ID);
ALTER TABLE CATEGORY ADD PRIMARY KEY (CATEGORY_ID);
ALTER TABLE PROVIDER ADD PRIMARY KEY (PROVIDER_ID);
ALTER TABLE AUDIO_BOOK ADD CONSTRAINT AUDIO_BOOK_provider_FK FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER (PROVIDER_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AUDIO_BOOK ADD CONSTRAINT AUDIO_BOOK_narrator_FK FOREIGN KEY (NARRATOR_ID) REFERENCES AUTHOR (AUTHOR_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AUDIO_BOOK_AUTHOR ADD CONSTRAINT AUDIO_BOOK_AUTHOR_author_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (AUTHOR_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AUDIO_BOOK_AUTHOR ADD CONSTRAINT AUDIO_BOOK_AUTHOR_audioBook_FK FOREIGN KEY (AUDIO_BOOK_ID) REFERENCES AUDIO_BOOK (AUDIO_BOOK_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AUDIO_BOOK_CATEGORY ADD CONSTRAINT AUDIO_BOOK_CATEGORY_category_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE AUDIO_BOOK_CATEGORY ADD CONSTRAINT AUDIO_BOOK_CATEGORY_audioBook_FK FOREIGN KEY (AUDIO_BOOK_ID) REFERENCES AUDIO_BOOK (AUDIO_BOOK_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE CATEGORY ADD CONSTRAINT CATEGORY_parent_FK FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID) DEFERRABLE INITIALLY DEFERRED;

-- Primary key support
create sequence AUDIO_BOOK_SEQ;
create sequence AUDIO_BOOK_AUTHOR_SEQ;
create sequence AUDIO_BOOK_CATEGORY_SEQ;
create sequence AUTHOR_SEQ;
create sequence CATEGORY_SEQ;
create sequence PROVIDER_SEQ;

-- Synonyms
create public synonym AUDIO_BOOK for AUDIO_BOOK;
create public synonym AUDIO_BOOK_AUTHOR for AUDIO_BOOK_AUTHOR;
create public synonym AUDIO_BOOK_CATEGORY for AUDIO_BOOK_CATEGORY;
create public synonym AUTHOR for AUTHOR;
create public synonym CATEGORY for CATEGORY;
create public synonym PROVIDER for PROVIDER;

------------------------------------
-- Table creation for Artists.eomodeld
------------------------------------

CREATE TABLE ARTIST (ARTIST_ID NUMBER(9) NOT NULL, ENTITY_NAME VARCHAR2(50) NOT NULL, LABEL_ID NUMBER(9) , NAME VARCHAR2(255) NOT NULL, FIRST_ARTIST_ID NUMBER(9) , SECOND_ARTIST_ID NUMBER(9) );

-- Primary key constraints
ALTER TABLE ARTIST ADD PRIMARY KEY (ARTIST_ID);
ALTER TABLE ARTIST ADD CONSTRAINT ARTIST_secondArtist_FK FOREIGN KEY (SECOND_ARTIST_ID) REFERENCES ARTIST (ARTIST_ID) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ARTIST ADD CONSTRAINT ARTIST_firstArtist_FK FOREIGN KEY (FIRST_ARTIST_ID) REFERENCES ARTIST (ARTIST_ID) DEFERRABLE INITIALLY DEFERRED;

-- Primary key support
create sequence ARTIST_SEQ;

-- Synonyms
create public synonym ARTIST for ARTIST;