// Generated by the WOLips Templateengine Plug-in at Mar 20, 2008 11:37:22 PM


import com.webobjects.appserver.WOApplication;
import com.webobjects.appserver._private.WODirectActionRequestHandler;
import com.webobjects.foundation.NSLog;

public class Application extends WOApplication {

    public static void main(String argv[]) {
        WOApplication.main(argv, Application.class);
    }

    public Application() {
        super();
        NSLog.out.appendln("Welcome to " + this.name() + " !");
        /* ** put your initialization code in here ** */
        application().setDefaultRequestHandler(WODirectActionRequestHandler.handler());
    }
}