// Generated by the WOLips Templateengine Plug-in at Mar 20, 2008 11:37:22 PM


import com.webobjects.appserver.*;

public class DirectAction extends WODirectAction {

    public DirectAction(WORequest aRequest) {
        super(aRequest);
    }

    public WOActionResults defaultAction() {
        return pageWithName("Main");
    }

}