// Generated by the WOLips Templateengine Plug-in at Mar 20, 2008 11:37:22 PM


import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
private static final long serialVersionUID = -1971330882910793648L;
}