// Generated by the WOLips Templateengine Plug-in at Apr 16, 2009 3:00:19 PM
import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
