package com.webobjects.directtoiphone;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at Mar 20, 2008 10:49:03 PM
public class D2TEdgeToEdgeListPage extends D2TListPage {
	public boolean showSearchdialog;
	
    public D2TEdgeToEdgeListPage(WOContext context) {
        super(context);
    }
    
    // accessors
    public String searchString() {
    	String key = displayPropertyKey();
    	return (String) valueForKeyPath("displayGroup.queryMatch." + key);
    }
    
    public void setSearchString(String value) {
    	String key = displayPropertyKey();
    	takeValueForKeyPath(value, "displayGroup.queryMatch." + key);
    }
    
    // actions
    public WOComponent toggleSearch() {
    	// toggle
    	showSearchdialog = !showSearchdialog;
    	return this;
    }
    
    public WOComponent search() {
    	displayGroup().qualifyDataSource();
    	return toggleSearch();
    }
}