// Generated by the WOLips Templateengine Plug-in at Apr 16, 2009 3:00:19 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {
	private static final long serialVersionUID = 1L;

	public Main(WOContext context) {
		super(context);
	}
	
	// accessors
	public String jQuerySrc() {
		return application().resourceManager().urlForResourceNamed("jquery-1.3.1.js", "jQuery", null, context().request());
	}
	
	public String svgPluginSrc() {
		return application().resourceManager().urlForResourceNamed("jquery.svg.js", "jQuery", null, context().request());
	}
}
