// Generated by the WOLips Templateengine Plug-in at Mar 20, 2008 11:37:22 PM
package com.mycompany;

import com.webobjects.appserver.*;

public class PageWrapper extends WOComponent {
	private static final long serialVersionUID = 1L;
    public PageWrapper(WOContext aContext) {
        super(aContext);
    }
}
